### ISSUE TITLE
An implementation issue in prepare_pascal.py

### ISSUE THREAD

**Issue by yangbosung1004** [MahdiShAhmadi/ReDMark#13]
In prepare_pascal.py, i think some code should be change.

From the line 22 should be changed. 
21        save_path = './images/pascal'
22        if os.path.exists(save_path):   --> if not os.path.exists(save_path)
23            os.makedirs(save_path)

In line 38 and line 41, the file paths are not the same. 
38       sio.savemat('./images/pascal_patches.mat', {'patches': concat_patches})
41       x_train = sio.loadmat('./images/pascal/pascal_patches.mat')['patches']

Thanks.

**Comment by hydayat** [comment]
It really heps!

**Comment by MahdiShAhmadi** [comment]
Thank you for your suggestions
