### ISSUE TITLE
Fail to run train.py 

### ISSUE THREAD

**Issue by hydayat** [MahdiShAhmadi/ReDMark#14]
Hi, I'm a graduate student interested in digital watermarking, and I'm trying to use ReDMark. However, when I run Train.py, it says that I miss the file "**./images/pascal/pascal_resampled.mat**".  Could you please tell me where can I get this file? Thanks for your help.

**Comment by maalyasein19** [comment]
do you get any solution to this problem??

**Comment by hydayat** [comment]
> 

Yes. You should run prepare_pascal.py first.
