### ISSUE TITLE
Adapting Model for COCO Dataset

### ISSUE THREAD

**Issue by HorizonXYH** [MahdiShAhmadi/ReDMark#20]
hello！Your paper is very intriguing, and I am interested in conducting some comparative experiments. I encountered several issues and errors while attempting to train the model with the COCO dataset. Does your code support swapping out datasets for experimentation?

**Comment by MahdiShAhmadi** [comment]
Hi, thank you for your kind words. Yes, you can use the code for whatever dataset you want but not as a parameter. Therefore, you need to make the necessary modifications according to your use case.
