### ISSUE TITLE
Need .m codes for transforms performed

### ISSUE THREAD

**Issue by ypradhan222** [MahdiShAhmadi/ReDMark#23]
Hello authors,
Can you also share the .m files for the transforms you have performed on each cover and watermarked images.

**Comment by MahdiShAhmadi** [comment]
Hello, I couldn't find the .m files. I am pretty sure I had them on my old laptop. If I find them somewhere, I will send them to you. Sorry for that.

**Comment by ypradhan222** [comment]
Thank You for your response. Sure, when you find them you can send me the
files.
