### ISSUE TITLE
About DCT layer and circular layer

### ISSUE THREAD

**Issue by SaltyFishhh** [MahdiShAhmadi/ReDMark#5]
hello~ 
Is the DCT layer equal to the convolution layer of 1x1？
Can the circular layer be replaced by 3x3 convolution layer？

**Comment by MahdiShAhmadi** [comment]
Hi,
- DCT layer **IS** a convolution layer of 1x1 with constant predefined weights.
- No, a [circular convolution](https://en.wikipedia.org/wiki/Circular_convolution) is different than typical convolutions. In the code you can change it and have non-circular convolutions; however, the quality and robustness performances will decrease.

**Comment by SaltyFishhh** [comment]
Thanks for your reply, a circular convolution consists of four 2x2 convolution. If it replace four 2x2 convolution with four 3x3 convolution, it should have a wider receptive field. Will this lead to a decline in robustness and performances?

**Comment by MahdiShAhmadi** [comment]
Let me modify your question a bit. The encoder network consists of four 2x2 circular convolution layers and some non-circular. 
Your answer: If we use 3x3 circular convolutions instead, this may lead to better or worse robustness and quality tradeoffs. Only by test we can find out.

**Comment by SaltyFishhh** [comment]
> Let me modify your question a bit. The encoder network consists of four 2x2 circular convolution layers and some non-circular.
> Your answer: If we use 3x3 circular convolutions instead, this may lead to better or worse robustness and quality tradeoffs. Only by test we can find out.
My English is not good, I hope you understand. Have you ever tried other circular convolution except the circular convolution that you proposed in your paper?

**Comment by MahdiShAhmadi** [comment]
Sorry for my late response! Yes we have tried.
