### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by fujiaixin09** [MahdiShAhmadi/ReDMark#6]
Hello! Thank you so much for the project you shared. When I run the test.py file, it is correct if I use the 49 grayscale images provided by you, but when I use other grayscale images to test, the pictures in the "Sampled Embeddings" folder are all black pictures? If I want to test a color picture, something went wrong?

**Comment by fujiaixin09** [comment]
There will be an error when running with another grayscale."ValueError: could not broadcast input array from shape (32,32,4) into shape (32,32)",Can you help me?

**Comment by MahdiShAhmadi** [comment]
This issue is resolved [here](https://github.com/MahdiShAhmadi/ReDMark/issues/7)
