### ISSUE TITLE
"transforms" folder

### ISSUE THREAD

**Issue by fujiaixin09** [MahdiShAhmadi/ReDMark#7]
How did the author get the mat file under the "transforms" folder?

**Comment by MahdiShAhmadi** [comment]
The files are obtained by the formulas at appendix section in our paper. The paper name is "ReDMark: Framework for Residual Diffusion Watermarking based on Deep Networks"

**Comment by fujiaixin09** [comment]
> The files are obtained by the formulas at appendix section in our paper. The paper name is "ReDMark: Framework for Residual Diffusion Watermarking based on Deep Networks"
Thank you for your quick reply！
- ReDMark algorithm can only discuss the gray image in this article. Can it be used for color image?


1. 

1.

**Comment by fujiaixin09** [comment]
> The files are obtained by the formulas at appendix section in our paper. The paper name is "ReDMark: Framework for Residual Diffusion Watermarking based on Deep Networks"
Thank you for your quick reply！

1. Redmark algorithm can only discuss the gray image in this article. Can it be used for color image?

**Comment by fujiaixin09** [comment]
> The files are obtained by the formulas at appendix section in our paper. The paper name is "ReDMark: Framework for Residual Diffusion Watermarking based on Deep Networks"


Thank you for your quick reply！

Redmark algorithm can only discuss the gray image in this article. Can it be used for color image?

**Comment by MahdiShAhmadi** [comment]
To use our algorithm on color images, we used our trained networks and embedded in different channels separately. For example, in section 4.5 of ReDMark paper, we compared our network to the results of HiDDeN on COCO dataset whose images are all colored images.

**Comment by fujiaixin09** [comment]
> To use our algorithm on color images, we used our trained networks and embedded in different channels separately. For example, in section 4.5 of ReDMark paper, we compared our network to the results of HiDDeN on COCO dataset whose images are all colored images.

Thank you for your prompt reply！
In DCT block transformation, it is operated with an 8 * 8 matrix, but why is the ". mat" file in the "transformations" folder a matrix size of 64 * 64.

**Comment by MahdiShAhmadi** [comment]
According to DCT formula, when you want to obtain one of 8x8=64 DCT coefficients, you need all 8x8=64 spatial coefficients.
As mentioned in the paper's 3.1.1. section, we did not handle it in a 2D manner (though we could do it in a more complicated setting); instead we reordered the coefficients as a 64x1 vector. By this trick we can simply obtain the DCT of the vector by a matrix multiplication.
